// DESIGN-GAP: Stable deck order is majors 0–21, then wands/cups/swords/pentacles Ace–King.
// DESIGN-GAP: Astrology mirrors content/tarot/cards.yaml; courts use their principal zodiac sign and elemental majors use modern rulers.
export const TAROT_CARDS = [
  {
    key: 'major_00_fool',
    number: 0,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'uranus',
    numerology: 0,
    yesNo: 'maybe',
  },
  {
    key: 'major_01_magician',
    number: 1,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'mercury',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'major_02_high_priestess',
    number: 2,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'moon',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'major_03_empress',
    number: 3,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'venus',
    numerology: 3,
    yesNo: 'yes',
  },
  {
    key: 'major_04_emperor',
    number: 4,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'aries',
    numerology: 4,
    yesNo: 'yes',
  },
  {
    key: 'major_05_hierophant',
    number: 5,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'taurus',
    numerology: 5,
    yesNo: 'maybe',
  },
  {
    key: 'major_06_lovers',
    number: 6,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'gemini',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'major_07_chariot',
    number: 7,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'cancer',
    numerology: 7,
    yesNo: 'yes',
  },
  {
    key: 'major_08_strength',
    number: 8,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'leo',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'major_09_hermit',
    number: 9,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'virgo',
    numerology: 9,
    yesNo: 'maybe',
  },
  {
    key: 'major_10_wheel_of_fortune',
    number: 10,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'jupiter',
    numerology: 10,
    yesNo: 'maybe',
  },
  {
    key: 'major_11_justice',
    number: 11,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'libra',
    numerology: 11,
    yesNo: 'maybe',
  },
  {
    key: 'major_12_hanged_man',
    number: 12,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'neptune',
    numerology: 12,
    yesNo: 'maybe',
  },
  {
    key: 'major_13_death',
    number: 13,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'scorpio',
    numerology: 13,
    yesNo: 'no',
  },
  {
    key: 'major_14_temperance',
    number: 14,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'sagittarius',
    numerology: 14,
    yesNo: 'yes',
  },
  {
    key: 'major_15_devil',
    number: 15,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'capricorn',
    numerology: 15,
    yesNo: 'no',
  },
  {
    key: 'major_16_tower',
    number: 16,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'mars',
    numerology: 16,
    yesNo: 'no',
  },
  {
    key: 'major_17_star',
    number: 17,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'aquarius',
    numerology: 17,
    yesNo: 'yes',
  },
  {
    key: 'major_18_moon',
    number: 18,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'pisces',
    numerology: 18,
    yesNo: 'maybe',
  },
  {
    key: 'major_19_sun',
    number: 19,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'sun',
    numerology: 19,
    yesNo: 'yes',
  },
  {
    key: 'major_20_judgement',
    number: 20,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'pluto',
    numerology: 20,
    yesNo: 'maybe',
  },
  {
    key: 'major_21_world',
    number: 21,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'saturn',
    numerology: 21,
    yesNo: 'yes',
  },
  {
    key: 'wands_01',
    number: 1,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'element_fire',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'wands_02',
    number: 2,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'mars_in_aries',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'wands_03',
    number: 3,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'sun_in_aries',
    numerology: 3,
    yesNo: 'yes',
  },
  {
    key: 'wands_04',
    number: 4,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'venus_in_aries',
    numerology: 4,
    yesNo: 'maybe',
  },
  {
    key: 'wands_05',
    number: 5,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'saturn_in_leo',
    numerology: 5,
    yesNo: 'maybe',
  },
  {
    key: 'wands_06',
    number: 6,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'jupiter_in_leo',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'wands_07',
    number: 7,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'mars_in_leo',
    numerology: 7,
    yesNo: 'maybe',
  },
  {
    key: 'wands_08',
    number: 8,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'mercury_in_sagittarius',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'wands_09',
    number: 9,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'moon_in_sagittarius',
    numerology: 9,
    yesNo: 'yes',
  },
  {
    key: 'wands_10',
    number: 10,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'saturn_in_sagittarius',
    numerology: 10,
    yesNo: 'yes',
  },
  {
    key: 'wands_page',
    number: 11,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'element_fire',
    numerology: 11,
    yesNo: 'yes',
  },
  {
    key: 'wands_knight',
    number: 12,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'leo',
    numerology: 12,
    yesNo: 'yes',
  },
  {
    key: 'wands_queen',
    number: 13,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'aries',
    numerology: 13,
    yesNo: 'yes',
  },
  {
    key: 'wands_king',
    number: 14,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'sagittarius',
    numerology: 14,
    yesNo: 'yes',
  },
  {
    key: 'cups_01',
    number: 1,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'element_water',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'cups_02',
    number: 2,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'venus_in_cancer',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'cups_03',
    number: 3,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'mercury_in_cancer',
    numerology: 3,
    yesNo: 'yes',
  },
  {
    key: 'cups_04',
    number: 4,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'moon_in_cancer',
    numerology: 4,
    yesNo: 'maybe',
  },
  {
    key: 'cups_05',
    number: 5,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'mars_in_scorpio',
    numerology: 5,
    yesNo: 'maybe',
  },
  {
    key: 'cups_06',
    number: 6,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'sun_in_scorpio',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'cups_07',
    number: 7,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'venus_in_scorpio',
    numerology: 7,
    yesNo: 'maybe',
  },
  {
    key: 'cups_08',
    number: 8,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'saturn_in_pisces',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'cups_09',
    number: 9,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'jupiter_in_pisces',
    numerology: 9,
    yesNo: 'yes',
  },
  {
    key: 'cups_10',
    number: 10,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'mars_in_pisces',
    numerology: 10,
    yesNo: 'yes',
  },
  {
    key: 'cups_page',
    number: 11,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'element_water',
    numerology: 11,
    yesNo: 'yes',
  },
  {
    key: 'cups_knight',
    number: 12,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'scorpio',
    numerology: 12,
    yesNo: 'yes',
  },
  {
    key: 'cups_queen',
    number: 13,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'cancer',
    numerology: 13,
    yesNo: 'yes',
  },
  {
    key: 'cups_king',
    number: 14,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'pisces',
    numerology: 14,
    yesNo: 'yes',
  },
  {
    key: 'swords_01',
    number: 1,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'element_air',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'swords_02',
    number: 2,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'moon_in_libra',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'swords_03',
    number: 3,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'saturn_in_libra',
    numerology: 3,
    yesNo: 'no',
  },
  {
    key: 'swords_04',
    number: 4,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'jupiter_in_libra',
    numerology: 4,
    yesNo: 'maybe',
  },
  {
    key: 'swords_05',
    number: 5,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'venus_in_aquarius',
    numerology: 5,
    yesNo: 'no',
  },
  {
    key: 'swords_06',
    number: 6,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'mercury_in_aquarius',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'swords_07',
    number: 7,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'moon_in_aquarius',
    numerology: 7,
    yesNo: 'maybe',
  },
  {
    key: 'swords_08',
    number: 8,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'jupiter_in_gemini',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'swords_09',
    number: 9,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'mars_in_gemini',
    numerology: 9,
    yesNo: 'no',
  },
  {
    key: 'swords_10',
    number: 10,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'sun_in_gemini',
    numerology: 10,
    yesNo: 'no',
  },
  {
    key: 'swords_page',
    number: 11,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'element_air',
    numerology: 11,
    yesNo: 'yes',
  },
  {
    key: 'swords_knight',
    number: 12,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'aquarius',
    numerology: 12,
    yesNo: 'yes',
  },
  {
    key: 'swords_queen',
    number: 13,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'libra',
    numerology: 13,
    yesNo: 'yes',
  },
  {
    key: 'swords_king',
    number: 14,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'gemini',
    numerology: 14,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_01',
    number: 1,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'element_earth',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_02',
    number: 2,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'jupiter_in_capricorn',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'pentacles_03',
    number: 3,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'mars_in_capricorn',
    numerology: 3,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_04',
    number: 4,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'sun_in_capricorn',
    numerology: 4,
    yesNo: 'maybe',
  },
  {
    key: 'pentacles_05',
    number: 5,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'mercury_in_taurus',
    numerology: 5,
    yesNo: 'maybe',
  },
  {
    key: 'pentacles_06',
    number: 6,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'moon_in_taurus',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_07',
    number: 7,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'saturn_in_taurus',
    numerology: 7,
    yesNo: 'maybe',
  },
  {
    key: 'pentacles_08',
    number: 8,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'sun_in_virgo',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_09',
    number: 9,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'venus_in_virgo',
    numerology: 9,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_10',
    number: 10,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'mercury_in_virgo',
    numerology: 10,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_page',
    number: 11,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'element_earth',
    numerology: 11,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_knight',
    number: 12,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'taurus',
    numerology: 12,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_queen',
    number: 13,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'capricorn',
    numerology: 13,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_king',
    number: 14,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'virgo',
    numerology: 14,
    yesNo: 'yes',
  },
] as const;
export type CardKey = (typeof TAROT_CARDS)[number]['key'];
