/** Immutable RWS deck metadata in canonical card order. */
export const TAROT_SWORDS = [
  {
    key: 'swords_01',
    number: 1,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'element_air',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'swords_02',
    number: 2,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'moon_in_libra',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'swords_03',
    number: 3,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'saturn_in_libra',
    numerology: 3,
    yesNo: 'no',
  },
  {
    key: 'swords_04',
    number: 4,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'jupiter_in_libra',
    numerology: 4,
    yesNo: 'maybe',
  },
  {
    key: 'swords_05',
    number: 5,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'venus_in_aquarius',
    numerology: 5,
    yesNo: 'no',
  },
  {
    key: 'swords_06',
    number: 6,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'mercury_in_aquarius',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'swords_07',
    number: 7,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'moon_in_aquarius',
    numerology: 7,
    yesNo: 'maybe',
  },
  {
    key: 'swords_08',
    number: 8,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'jupiter_in_gemini',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'swords_09',
    number: 9,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'mars_in_gemini',
    numerology: 9,
    yesNo: 'no',
  },
  {
    key: 'swords_10',
    number: 10,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'sun_in_gemini',
    numerology: 10,
    yesNo: 'no',
  },
  {
    key: 'swords_page',
    number: 11,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'element_air',
    numerology: 11,
    yesNo: 'yes',
  },
  {
    key: 'swords_knight',
    number: 12,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'aquarius',
    numerology: 12,
    yesNo: 'yes',
  },
  {
    key: 'swords_queen',
    number: 13,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'libra',
    numerology: 13,
    yesNo: 'yes',
  },
  {
    key: 'swords_king',
    number: 14,
    arcana: 'minor',
    suit: 'swords',
    element: 'air',
    astrology: 'gemini',
    numerology: 14,
    yesNo: 'yes',
  },
] as const;
