/** Immutable RWS deck metadata in canonical card order. */
export const TAROT_PENTACLES = [
  {
    key: 'pentacles_01',
    number: 1,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'element_earth',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_02',
    number: 2,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'jupiter_in_capricorn',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'pentacles_03',
    number: 3,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'mars_in_capricorn',
    numerology: 3,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_04',
    number: 4,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'sun_in_capricorn',
    numerology: 4,
    yesNo: 'maybe',
  },
  {
    key: 'pentacles_05',
    number: 5,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'mercury_in_taurus',
    numerology: 5,
    yesNo: 'maybe',
  },
  {
    key: 'pentacles_06',
    number: 6,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'moon_in_taurus',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_07',
    number: 7,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'saturn_in_taurus',
    numerology: 7,
    yesNo: 'maybe',
  },
  {
    key: 'pentacles_08',
    number: 8,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'sun_in_virgo',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_09',
    number: 9,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'venus_in_virgo',
    numerology: 9,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_10',
    number: 10,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'mercury_in_virgo',
    numerology: 10,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_page',
    number: 11,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'element_earth',
    numerology: 11,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_knight',
    number: 12,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'taurus',
    numerology: 12,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_queen',
    number: 13,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'capricorn',
    numerology: 13,
    yesNo: 'yes',
  },
  {
    key: 'pentacles_king',
    number: 14,
    arcana: 'minor',
    suit: 'pentacles',
    element: 'earth',
    astrology: 'virgo',
    numerology: 14,
    yesNo: 'yes',
  },
] as const;
