// DESIGN-GAP: Unspecified coordinates use the conventional layout in content/tarot/spreads.yaml.
export const TAROT_SPREADS = {
  single: [
    {
      key: 'focus',
      x: 0.5,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
  ],
  yes_no: [
    {
      key: 'answer',
      x: 0.5,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
  ],
  three_ppf: [
    {
      key: 'past',
      x: 0.2,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'present',
      x: 0.5,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'future',
      x: 0.8,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
  ],
  three_sao: [
    {
      key: 'situation',
      x: 0.2,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'action',
      x: 0.5,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'outcome',
      x: 0.8,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
  ],
  relationship: [
    {
      key: 'you',
      x: 0.25,
      y: 0.35,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'them',
      x: 0.75,
      y: 0.35,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'connection',
      x: 0.5,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'challenge',
      x: 0.5,
      y: 0.8,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'potential',
      x: 0.5,
      y: 0.15,
      rotation: 0,
      readUpright: false,
    },
  ],
  decision: [
    {
      key: 'situation',
      x: 0.5,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'option_a',
      x: 0.2,
      y: 0.3,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'option_a_outcome',
      x: 0.2,
      y: 0.7,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'option_b',
      x: 0.8,
      y: 0.3,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'option_b_outcome',
      x: 0.8,
      y: 0.7,
      rotation: 0,
      readUpright: false,
    },
  ],
  celtic_cross: [
    {
      key: 'present',
      x: 0.35,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'challenge',
      x: 0.35,
      y: 0.5,
      rotation: 90,
      readUpright: true,
    },
    {
      key: 'foundation',
      x: 0.35,
      y: 0.8,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'past',
      x: 0.1,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'crown',
      x: 0.35,
      y: 0.2,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'near_future',
      x: 0.6,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'self',
      x: 0.85,
      y: 0.85,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'environment',
      x: 0.85,
      y: 0.62,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'hopes_fears',
      x: 0.85,
      y: 0.38,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'outcome',
      x: 0.85,
      y: 0.15,
      rotation: 0,
      readUpright: false,
    },
  ],
  year_ahead: [
    {
      key: 'theme',
      x: 0.5,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm01',
      x: 0.5,
      y: 0.08,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm02',
      x: 0.71,
      y: 0.136269,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm03',
      x: 0.863731,
      y: 0.29,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm04',
      x: 0.92,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm05',
      x: 0.863731,
      y: 0.71,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm06',
      x: 0.71,
      y: 0.863731,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm07',
      x: 0.5,
      y: 0.92,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm08',
      x: 0.29,
      y: 0.863731,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm09',
      x: 0.136269,
      y: 0.71,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm10',
      x: 0.08,
      y: 0.5,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm11',
      x: 0.136269,
      y: 0.29,
      rotation: 0,
      readUpright: false,
    },
    {
      key: 'm12',
      x: 0.29,
      y: 0.136269,
      rotation: 0,
      readUpright: false,
    },
  ],
} as const;
export type SpreadKey = keyof typeof TAROT_SPREADS;
