/** Immutable RWS deck metadata in canonical card order. */
export const TAROT_WANDS = [
  {
    key: 'wands_01',
    number: 1,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'element_fire',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'wands_02',
    number: 2,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'mars_in_aries',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'wands_03',
    number: 3,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'sun_in_aries',
    numerology: 3,
    yesNo: 'yes',
  },
  {
    key: 'wands_04',
    number: 4,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'venus_in_aries',
    numerology: 4,
    yesNo: 'maybe',
  },
  {
    key: 'wands_05',
    number: 5,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'saturn_in_leo',
    numerology: 5,
    yesNo: 'maybe',
  },
  {
    key: 'wands_06',
    number: 6,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'jupiter_in_leo',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'wands_07',
    number: 7,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'mars_in_leo',
    numerology: 7,
    yesNo: 'maybe',
  },
  {
    key: 'wands_08',
    number: 8,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'mercury_in_sagittarius',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'wands_09',
    number: 9,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'moon_in_sagittarius',
    numerology: 9,
    yesNo: 'yes',
  },
  {
    key: 'wands_10',
    number: 10,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'saturn_in_sagittarius',
    numerology: 10,
    yesNo: 'yes',
  },
  {
    key: 'wands_page',
    number: 11,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'element_fire',
    numerology: 11,
    yesNo: 'yes',
  },
  {
    key: 'wands_knight',
    number: 12,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'leo',
    numerology: 12,
    yesNo: 'yes',
  },
  {
    key: 'wands_queen',
    number: 13,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'aries',
    numerology: 13,
    yesNo: 'yes',
  },
  {
    key: 'wands_king',
    number: 14,
    arcana: 'minor',
    suit: 'wands',
    element: 'fire',
    astrology: 'sagittarius',
    numerology: 14,
    yesNo: 'yes',
  },
] as const;
