/** Immutable RWS deck metadata in canonical card order. */
export const TAROT_CUPS = [
  {
    key: 'cups_01',
    number: 1,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'element_water',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'cups_02',
    number: 2,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'venus_in_cancer',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'cups_03',
    number: 3,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'mercury_in_cancer',
    numerology: 3,
    yesNo: 'yes',
  },
  {
    key: 'cups_04',
    number: 4,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'moon_in_cancer',
    numerology: 4,
    yesNo: 'maybe',
  },
  {
    key: 'cups_05',
    number: 5,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'mars_in_scorpio',
    numerology: 5,
    yesNo: 'maybe',
  },
  {
    key: 'cups_06',
    number: 6,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'sun_in_scorpio',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'cups_07',
    number: 7,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'venus_in_scorpio',
    numerology: 7,
    yesNo: 'maybe',
  },
  {
    key: 'cups_08',
    number: 8,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'saturn_in_pisces',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'cups_09',
    number: 9,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'jupiter_in_pisces',
    numerology: 9,
    yesNo: 'yes',
  },
  {
    key: 'cups_10',
    number: 10,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'mars_in_pisces',
    numerology: 10,
    yesNo: 'yes',
  },
  {
    key: 'cups_page',
    number: 11,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'element_water',
    numerology: 11,
    yesNo: 'yes',
  },
  {
    key: 'cups_knight',
    number: 12,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'scorpio',
    numerology: 12,
    yesNo: 'yes',
  },
  {
    key: 'cups_queen',
    number: 13,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'cancer',
    numerology: 13,
    yesNo: 'yes',
  },
  {
    key: 'cups_king',
    number: 14,
    arcana: 'minor',
    suit: 'cups',
    element: 'water',
    astrology: 'pisces',
    numerology: 14,
    yesNo: 'yes',
  },
] as const;
