/** Immutable RWS deck metadata in canonical card order. */
export const TAROT_MAJOR_CARDS = [
  {
    key: 'major_00_fool',
    number: 0,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'uranus',
    numerology: 0,
    yesNo: 'maybe',
  },
  {
    key: 'major_01_magician',
    number: 1,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'mercury',
    numerology: 1,
    yesNo: 'yes',
  },
  {
    key: 'major_02_high_priestess',
    number: 2,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'moon',
    numerology: 2,
    yesNo: 'maybe',
  },
  {
    key: 'major_03_empress',
    number: 3,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'venus',
    numerology: 3,
    yesNo: 'yes',
  },
  {
    key: 'major_04_emperor',
    number: 4,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'aries',
    numerology: 4,
    yesNo: 'yes',
  },
  {
    key: 'major_05_hierophant',
    number: 5,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'taurus',
    numerology: 5,
    yesNo: 'maybe',
  },
  {
    key: 'major_06_lovers',
    number: 6,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'gemini',
    numerology: 6,
    yesNo: 'yes',
  },
  {
    key: 'major_07_chariot',
    number: 7,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'cancer',
    numerology: 7,
    yesNo: 'yes',
  },
  {
    key: 'major_08_strength',
    number: 8,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'leo',
    numerology: 8,
    yesNo: 'yes',
  },
  {
    key: 'major_09_hermit',
    number: 9,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'virgo',
    numerology: 9,
    yesNo: 'maybe',
  },
  {
    key: 'major_10_wheel_of_fortune',
    number: 10,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'jupiter',
    numerology: 10,
    yesNo: 'maybe',
  },
  {
    key: 'major_11_justice',
    number: 11,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'libra',
    numerology: 11,
    yesNo: 'maybe',
  },
  {
    key: 'major_12_hanged_man',
    number: 12,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'neptune',
    numerology: 12,
    yesNo: 'maybe',
  },
  {
    key: 'major_13_death',
    number: 13,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'scorpio',
    numerology: 13,
    yesNo: 'no',
  },
  {
    key: 'major_14_temperance',
    number: 14,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'sagittarius',
    numerology: 14,
    yesNo: 'yes',
  },
  {
    key: 'major_15_devil',
    number: 15,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'capricorn',
    numerology: 15,
    yesNo: 'no',
  },
  {
    key: 'major_16_tower',
    number: 16,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'mars',
    numerology: 16,
    yesNo: 'no',
  },
  {
    key: 'major_17_star',
    number: 17,
    arcana: 'major',
    suit: null,
    element: 'air',
    astrology: 'aquarius',
    numerology: 17,
    yesNo: 'yes',
  },
  {
    key: 'major_18_moon',
    number: 18,
    arcana: 'major',
    suit: null,
    element: 'water',
    astrology: 'pisces',
    numerology: 18,
    yesNo: 'maybe',
  },
  {
    key: 'major_19_sun',
    number: 19,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'sun',
    numerology: 19,
    yesNo: 'yes',
  },
  {
    key: 'major_20_judgement',
    number: 20,
    arcana: 'major',
    suit: null,
    element: 'fire',
    astrology: 'pluto',
    numerology: 20,
    yesNo: 'maybe',
  },
  {
    key: 'major_21_world',
    number: 21,
    arcana: 'major',
    suit: null,
    element: 'earth',
    astrology: 'saturn',
    numerology: 21,
    yesNo: 'yes',
  },
] as const;
