/** Immutable King Wen topology in canonical hexagram order. */
export const HEXAGRAM_DATA_UPPER = [
  {
    number: 1,
    key: 'hexagram_01',
    lines: [1, 1, 1, 1, 1, 1],
    upper: 'qian',
    lower: 'qian',
  },
  {
    number: 2,
    key: 'hexagram_02',
    lines: [0, 0, 0, 0, 0, 0],
    upper: 'kun',
    lower: 'kun',
  },
  {
    number: 3,
    key: 'hexagram_03',
    lines: [1, 0, 0, 0, 1, 0],
    upper: 'kan',
    lower: 'zhen',
  },
  {
    number: 4,
    key: 'hexagram_04',
    lines: [0, 1, 0, 0, 0, 1],
    upper: 'gen',
    lower: 'kan',
  },
  {
    number: 5,
    key: 'hexagram_05',
    lines: [1, 1, 1, 0, 1, 0],
    upper: 'kan',
    lower: 'qian',
  },
  {
    number: 6,
    key: 'hexagram_06',
    lines: [0, 1, 0, 1, 1, 1],
    upper: 'qian',
    lower: 'kan',
  },
  {
    number: 7,
    key: 'hexagram_07',
    lines: [0, 1, 0, 0, 0, 0],
    upper: 'kun',
    lower: 'kan',
  },
  {
    number: 8,
    key: 'hexagram_08',
    lines: [0, 0, 0, 0, 1, 0],
    upper: 'kan',
    lower: 'kun',
  },
  {
    number: 9,
    key: 'hexagram_09',
    lines: [1, 1, 1, 0, 1, 1],
    upper: 'xun',
    lower: 'qian',
  },
  {
    number: 10,
    key: 'hexagram_10',
    lines: [1, 1, 0, 1, 1, 1],
    upper: 'qian',
    lower: 'dui',
  },
  {
    number: 11,
    key: 'hexagram_11',
    lines: [1, 1, 1, 0, 0, 0],
    upper: 'kun',
    lower: 'qian',
  },
  {
    number: 12,
    key: 'hexagram_12',
    lines: [0, 0, 0, 1, 1, 1],
    upper: 'qian',
    lower: 'kun',
  },
  {
    number: 13,
    key: 'hexagram_13',
    lines: [1, 0, 1, 1, 1, 1],
    upper: 'qian',
    lower: 'li',
  },
  {
    number: 14,
    key: 'hexagram_14',
    lines: [1, 1, 1, 1, 0, 1],
    upper: 'li',
    lower: 'qian',
  },
  {
    number: 15,
    key: 'hexagram_15',
    lines: [0, 0, 1, 0, 0, 0],
    upper: 'kun',
    lower: 'gen',
  },
  {
    number: 16,
    key: 'hexagram_16',
    lines: [0, 0, 0, 1, 0, 0],
    upper: 'zhen',
    lower: 'kun',
  },
  {
    number: 17,
    key: 'hexagram_17',
    lines: [1, 0, 0, 1, 1, 0],
    upper: 'dui',
    lower: 'zhen',
  },
  {
    number: 18,
    key: 'hexagram_18',
    lines: [0, 1, 1, 0, 0, 1],
    upper: 'gen',
    lower: 'xun',
  },
  {
    number: 19,
    key: 'hexagram_19',
    lines: [1, 1, 0, 0, 0, 0],
    upper: 'kun',
    lower: 'dui',
  },
  {
    number: 20,
    key: 'hexagram_20',
    lines: [0, 0, 0, 0, 1, 1],
    upper: 'xun',
    lower: 'kun',
  },
  {
    number: 21,
    key: 'hexagram_21',
    lines: [1, 0, 0, 1, 0, 1],
    upper: 'li',
    lower: 'zhen',
  },
  {
    number: 22,
    key: 'hexagram_22',
    lines: [1, 0, 1, 0, 0, 1],
    upper: 'gen',
    lower: 'li',
  },
  {
    number: 23,
    key: 'hexagram_23',
    lines: [0, 0, 0, 0, 0, 1],
    upper: 'gen',
    lower: 'kun',
  },
  {
    number: 24,
    key: 'hexagram_24',
    lines: [1, 0, 0, 0, 0, 0],
    upper: 'kun',
    lower: 'zhen',
  },
  {
    number: 25,
    key: 'hexagram_25',
    lines: [1, 0, 0, 1, 1, 1],
    upper: 'qian',
    lower: 'zhen',
  },
  {
    number: 26,
    key: 'hexagram_26',
    lines: [1, 1, 1, 0, 0, 1],
    upper: 'gen',
    lower: 'qian',
  },
  {
    number: 27,
    key: 'hexagram_27',
    lines: [1, 0, 0, 0, 0, 1],
    upper: 'gen',
    lower: 'zhen',
  },
  {
    number: 28,
    key: 'hexagram_28',
    lines: [0, 1, 1, 1, 1, 0],
    upper: 'dui',
    lower: 'xun',
  },
  {
    number: 29,
    key: 'hexagram_29',
    lines: [0, 1, 0, 0, 1, 0],
    upper: 'kan',
    lower: 'kan',
  },
  {
    number: 30,
    key: 'hexagram_30',
    lines: [1, 0, 1, 1, 0, 1],
    upper: 'li',
    lower: 'li',
  },
  {
    number: 31,
    key: 'hexagram_31',
    lines: [0, 0, 1, 1, 1, 0],
    upper: 'dui',
    lower: 'gen',
  },
  {
    number: 32,
    key: 'hexagram_32',
    lines: [0, 1, 1, 1, 0, 0],
    upper: 'zhen',
    lower: 'xun',
  },
] as const;
