// Generated King Wen topology; provenance: packages/content/iching/source-audit.json.
export const HEXAGRAM_DATA = [
  {
    number: 1,
    key: 'hexagram_01',
    lines: [1, 1, 1, 1, 1, 1],
    upper: 'qian',
    lower: 'qian',
  },
  {
    number: 2,
    key: 'hexagram_02',
    lines: [0, 0, 0, 0, 0, 0],
    upper: 'kun',
    lower: 'kun',
  },
  {
    number: 3,
    key: 'hexagram_03',
    lines: [1, 0, 0, 0, 1, 0],
    upper: 'kan',
    lower: 'zhen',
  },
  {
    number: 4,
    key: 'hexagram_04',
    lines: [0, 1, 0, 0, 0, 1],
    upper: 'gen',
    lower: 'kan',
  },
  {
    number: 5,
    key: 'hexagram_05',
    lines: [1, 1, 1, 0, 1, 0],
    upper: 'kan',
    lower: 'qian',
  },
  {
    number: 6,
    key: 'hexagram_06',
    lines: [0, 1, 0, 1, 1, 1],
    upper: 'qian',
    lower: 'kan',
  },
  {
    number: 7,
    key: 'hexagram_07',
    lines: [0, 1, 0, 0, 0, 0],
    upper: 'kun',
    lower: 'kan',
  },
  {
    number: 8,
    key: 'hexagram_08',
    lines: [0, 0, 0, 0, 1, 0],
    upper: 'kan',
    lower: 'kun',
  },
  {
    number: 9,
    key: 'hexagram_09',
    lines: [1, 1, 1, 0, 1, 1],
    upper: 'xun',
    lower: 'qian',
  },
  {
    number: 10,
    key: 'hexagram_10',
    lines: [1, 1, 0, 1, 1, 1],
    upper: 'qian',
    lower: 'dui',
  },
  {
    number: 11,
    key: 'hexagram_11',
    lines: [1, 1, 1, 0, 0, 0],
    upper: 'kun',
    lower: 'qian',
  },
  {
    number: 12,
    key: 'hexagram_12',
    lines: [0, 0, 0, 1, 1, 1],
    upper: 'qian',
    lower: 'kun',
  },
  {
    number: 13,
    key: 'hexagram_13',
    lines: [1, 0, 1, 1, 1, 1],
    upper: 'qian',
    lower: 'li',
  },
  {
    number: 14,
    key: 'hexagram_14',
    lines: [1, 1, 1, 1, 0, 1],
    upper: 'li',
    lower: 'qian',
  },
  {
    number: 15,
    key: 'hexagram_15',
    lines: [0, 0, 1, 0, 0, 0],
    upper: 'kun',
    lower: 'gen',
  },
  {
    number: 16,
    key: 'hexagram_16',
    lines: [0, 0, 0, 1, 0, 0],
    upper: 'zhen',
    lower: 'kun',
  },
  {
    number: 17,
    key: 'hexagram_17',
    lines: [1, 0, 0, 1, 1, 0],
    upper: 'dui',
    lower: 'zhen',
  },
  {
    number: 18,
    key: 'hexagram_18',
    lines: [0, 1, 1, 0, 0, 1],
    upper: 'gen',
    lower: 'xun',
  },
  {
    number: 19,
    key: 'hexagram_19',
    lines: [1, 1, 0, 0, 0, 0],
    upper: 'kun',
    lower: 'dui',
  },
  {
    number: 20,
    key: 'hexagram_20',
    lines: [0, 0, 0, 0, 1, 1],
    upper: 'xun',
    lower: 'kun',
  },
  {
    number: 21,
    key: 'hexagram_21',
    lines: [1, 0, 0, 1, 0, 1],
    upper: 'li',
    lower: 'zhen',
  },
  {
    number: 22,
    key: 'hexagram_22',
    lines: [1, 0, 1, 0, 0, 1],
    upper: 'gen',
    lower: 'li',
  },
  {
    number: 23,
    key: 'hexagram_23',
    lines: [0, 0, 0, 0, 0, 1],
    upper: 'gen',
    lower: 'kun',
  },
  {
    number: 24,
    key: 'hexagram_24',
    lines: [1, 0, 0, 0, 0, 0],
    upper: 'kun',
    lower: 'zhen',
  },
  {
    number: 25,
    key: 'hexagram_25',
    lines: [1, 0, 0, 1, 1, 1],
    upper: 'qian',
    lower: 'zhen',
  },
  {
    number: 26,
    key: 'hexagram_26',
    lines: [1, 1, 1, 0, 0, 1],
    upper: 'gen',
    lower: 'qian',
  },
  {
    number: 27,
    key: 'hexagram_27',
    lines: [1, 0, 0, 0, 0, 1],
    upper: 'gen',
    lower: 'zhen',
  },
  {
    number: 28,
    key: 'hexagram_28',
    lines: [0, 1, 1, 1, 1, 0],
    upper: 'dui',
    lower: 'xun',
  },
  {
    number: 29,
    key: 'hexagram_29',
    lines: [0, 1, 0, 0, 1, 0],
    upper: 'kan',
    lower: 'kan',
  },
  {
    number: 30,
    key: 'hexagram_30',
    lines: [1, 0, 1, 1, 0, 1],
    upper: 'li',
    lower: 'li',
  },
  {
    number: 31,
    key: 'hexagram_31',
    lines: [0, 0, 1, 1, 1, 0],
    upper: 'dui',
    lower: 'gen',
  },
  {
    number: 32,
    key: 'hexagram_32',
    lines: [0, 1, 1, 1, 0, 0],
    upper: 'zhen',
    lower: 'xun',
  },
  {
    number: 33,
    key: 'hexagram_33',
    lines: [0, 0, 1, 1, 1, 1],
    upper: 'qian',
    lower: 'gen',
  },
  {
    number: 34,
    key: 'hexagram_34',
    lines: [1, 1, 1, 1, 0, 0],
    upper: 'zhen',
    lower: 'qian',
  },
  {
    number: 35,
    key: 'hexagram_35',
    lines: [0, 0, 0, 1, 0, 1],
    upper: 'li',
    lower: 'kun',
  },
  {
    number: 36,
    key: 'hexagram_36',
    lines: [1, 0, 1, 0, 0, 0],
    upper: 'kun',
    lower: 'li',
  },
  {
    number: 37,
    key: 'hexagram_37',
    lines: [1, 0, 1, 0, 1, 1],
    upper: 'xun',
    lower: 'li',
  },
  {
    number: 38,
    key: 'hexagram_38',
    lines: [1, 1, 0, 1, 0, 1],
    upper: 'li',
    lower: 'dui',
  },
  {
    number: 39,
    key: 'hexagram_39',
    lines: [0, 0, 1, 0, 1, 0],
    upper: 'kan',
    lower: 'gen',
  },
  {
    number: 40,
    key: 'hexagram_40',
    lines: [0, 1, 0, 1, 0, 0],
    upper: 'zhen',
    lower: 'kan',
  },
  {
    number: 41,
    key: 'hexagram_41',
    lines: [1, 1, 0, 0, 0, 1],
    upper: 'gen',
    lower: 'dui',
  },
  {
    number: 42,
    key: 'hexagram_42',
    lines: [1, 0, 0, 0, 1, 1],
    upper: 'xun',
    lower: 'zhen',
  },
  {
    number: 43,
    key: 'hexagram_43',
    lines: [1, 1, 1, 1, 1, 0],
    upper: 'dui',
    lower: 'qian',
  },
  {
    number: 44,
    key: 'hexagram_44',
    lines: [0, 1, 1, 1, 1, 1],
    upper: 'qian',
    lower: 'xun',
  },
  {
    number: 45,
    key: 'hexagram_45',
    lines: [0, 0, 0, 1, 1, 0],
    upper: 'dui',
    lower: 'kun',
  },
  {
    number: 46,
    key: 'hexagram_46',
    lines: [0, 1, 1, 0, 0, 0],
    upper: 'kun',
    lower: 'xun',
  },
  {
    number: 47,
    key: 'hexagram_47',
    lines: [0, 1, 0, 1, 1, 0],
    upper: 'dui',
    lower: 'kan',
  },
  {
    number: 48,
    key: 'hexagram_48',
    lines: [0, 1, 1, 0, 1, 0],
    upper: 'kan',
    lower: 'xun',
  },
  {
    number: 49,
    key: 'hexagram_49',
    lines: [1, 0, 1, 1, 1, 0],
    upper: 'dui',
    lower: 'li',
  },
  {
    number: 50,
    key: 'hexagram_50',
    lines: [0, 1, 1, 1, 0, 1],
    upper: 'li',
    lower: 'xun',
  },
  {
    number: 51,
    key: 'hexagram_51',
    lines: [1, 0, 0, 1, 0, 0],
    upper: 'zhen',
    lower: 'zhen',
  },
  {
    number: 52,
    key: 'hexagram_52',
    lines: [0, 0, 1, 0, 0, 1],
    upper: 'gen',
    lower: 'gen',
  },
  {
    number: 53,
    key: 'hexagram_53',
    lines: [0, 0, 1, 0, 1, 1],
    upper: 'xun',
    lower: 'gen',
  },
  {
    number: 54,
    key: 'hexagram_54',
    lines: [1, 1, 0, 1, 0, 0],
    upper: 'zhen',
    lower: 'dui',
  },
  {
    number: 55,
    key: 'hexagram_55',
    lines: [1, 0, 1, 1, 0, 0],
    upper: 'zhen',
    lower: 'li',
  },
  {
    number: 56,
    key: 'hexagram_56',
    lines: [0, 0, 1, 1, 0, 1],
    upper: 'li',
    lower: 'gen',
  },
  {
    number: 57,
    key: 'hexagram_57',
    lines: [0, 1, 1, 0, 1, 1],
    upper: 'xun',
    lower: 'xun',
  },
  {
    number: 58,
    key: 'hexagram_58',
    lines: [1, 1, 0, 1, 1, 0],
    upper: 'dui',
    lower: 'dui',
  },
  {
    number: 59,
    key: 'hexagram_59',
    lines: [0, 1, 0, 0, 1, 1],
    upper: 'xun',
    lower: 'kan',
  },
  {
    number: 60,
    key: 'hexagram_60',
    lines: [1, 1, 0, 0, 1, 0],
    upper: 'kan',
    lower: 'dui',
  },
  {
    number: 61,
    key: 'hexagram_61',
    lines: [1, 1, 0, 0, 1, 1],
    upper: 'xun',
    lower: 'dui',
  },
  {
    number: 62,
    key: 'hexagram_62',
    lines: [0, 0, 1, 1, 0, 0],
    upper: 'zhen',
    lower: 'gen',
  },
  {
    number: 63,
    key: 'hexagram_63',
    lines: [1, 0, 1, 0, 1, 0],
    upper: 'kan',
    lower: 'li',
  },
  {
    number: 64,
    key: 'hexagram_64',
    lines: [0, 1, 0, 1, 0, 1],
    upper: 'li',
    lower: 'kan',
  },
] as const;
