import { describe, expect, it } from 'vitest';
import { compute, computeNumerology, normalizeBirth, personalNumbers, reduceNumber } from '../src';
import { NumerologyChartSchema, NumerologyNameSchema, ReadingRequestSchema } from '@tianji/shared';
const now = '2026-10-05T00:00:00Z';
const birth = (year: number, month: number, day: number) =>
  normalizeBirth({
    calendar: 'gregorian',
    year,
    month,
    day,
    timeUnknown: true,
    gender: 'unspecified',
  });
// Golden totals are independently hand-added in docs/systems/numerology.md, not generated by the implementation.
const golden = [
  [1990, 5, 15, 30, 3],
  [1985, 11, 2, 27, 9],
  [2000, 2, 4, 8, 8],
  [1988, 7, 10, 34, 7],
  [1995, 8, 20, 34, 7],
  [1960, 1, 1, 18, 9],
  [2000, 1, 8, 11, 11],
  [2000, 9, 29, 22, 22],
  [1999, 1, 4, 33, 33],
  [2000, 2, 29, 15, 6],
  [1900, 1, 1, 12, 3],
  [2100, 12, 31, 10, 1],
  [2001, 1, 1, 5, 5],
  [2002, 2, 2, 8, 8],
  [2003, 3, 3, 11, 11],
  [2004, 4, 4, 14, 5],
  [2005, 5, 5, 17, 8],
  [2006, 6, 6, 20, 2],
  [2007, 7, 7, 23, 5],
  [2008, 8, 8, 26, 8],
  [2009, 9, 9, 29, 11],
  [1990, 1, 11, 22, 22],
  [1990, 1, 22, 24, 6],
] as const;
describe('numerology', () => {
  it.each(golden)('golden %i-%i-%i => total %i, number %i', (year, month, day, sum, number) => {
    const chart = computeNumerology({ birth: birth(year, month, day), date: '2026-10-05' });
    expect(chart.lifePath).toMatchObject({ sum, number });
    expect(NumerologyChartSchema.safeParse(chart).success).toBe(true);
    expect(chart.nameNumbers).toBeNull();
    expect(chart.grid.reduce((sum, c) => sum + c.count, 0)).toBe(
      `${year}${month}${day}`.replace(/0/g, '').length,
    );
  });
  it('uses the Pythagorean table and keeps no name text', () => {
    const chart = computeNumerology({
      birth: birth(1990, 5, 15),
      name: 'John Doe',
      date: '2026-10-05',
    });
    expect(chart.nameNumbers).toEqual({
      expression: { sum: 35, steps: [35, 8], number: 8 },
      soul: { sum: 17, steps: [17, 8], number: 8 },
      personality: { sum: 18, steps: [18, 9], number: 9 },
    });
    expect(JSON.stringify(chart)).not.toContain('John');
    expect(chart.compatibility).toEqual({ first: 3, second: 8, basis: 'expression' });
    expect(
      computeNumerology({ birth: birth(1990, 5, 15), name: 'john-doe', date: '2026-10-05' }),
    ).toEqual(chart);
  });
  it('classifies Y as a consonant and represents empty groups without zero types', () => {
    const amy = computeNumerology({ birth: birth(1990, 5, 15), name: 'Amy', date: '2026-10-05' });
    expect(amy.nameNumbers?.personality.number).toBe(11);
    expect(
      computeNumerology({ birth: birth(1990, 5, 15), name: 'Rhythm', date: '2026-10-05' })
        .nameNumbers?.soul.number,
    ).toBeNull();
    expect(
      computeNumerology({ birth: birth(1990, 5, 15), name: 'AEIOU', date: '2026-10-05' })
        .nameNumbers?.personality.number,
    ).toBeNull();
    expect(
      computeNumerology({ birth: birth(1990, 5, 15), name: ' ', date: '2026-10-05' }).nameNumbers,
    ).toBeNull();
  });
  it('checks all letter values against an independent table', () => {
    const table = '1234567891234567891234567891';
    for (const [index, letter] of Array.from('ABCDEFGHIJKLMNOPQRSTUVWXYZ').entries()) {
      const chart = computeNumerology({
        birth: birth(1990, 5, 15),
        name: letter,
        date: '2026-10-05',
      });
      expect(chart.nameNumbers?.expression.sum).toBe(Number(table[index]));
    }
  });
  it('reduces master numbers only outside natal/name numbers and handles zero', () => {
    expect(reduceNumber(11).number).toBe(11);
    expect(reduceNumber(22).number).toBe(22);
    expect(reduceNumber(33).number).toBe(33);
    expect(reduceNumber(38)).toEqual({ sum: 38, steps: [38, 11], number: 11 });
    expect(reduceNumber(11, false).number).toBe(2);
    expect(reduceNumber(0).number).toBeNull();
    for (const value of [-1, 1.2, Number.NaN, Number.MAX_SAFE_INTEGER + 1])
      expect(() => reduceNumber(value)).toThrow();
  });
  it('computes personal periods and switches years on January first', () => {
    expect(personalNumbers(5, 15, '2026-10-05')).toEqual({
      year: 3,
      month: 4,
      day: 9,
      targetDate: '2026-10-05',
    });
    expect(personalNumbers(5, 15, '2026-12-31').year).toBe(3);
    expect(personalNumbers(5, 15, '2027-01-01').year).toBe(4);
    expect(personalNumbers(5, 15, '2026-10-07').day).toBe(2);
    expect(personalNumbers(2, 29, '2026-02-28')).toMatchObject({ year: 5, month: 7, day: 8 });
    expect(() => personalNumbers(5, 15, '2026-02-30')).toThrow();
    for (const [month, day] of [
      [0, 15],
      [13, 15],
      [5, 0],
      [5, 32],
      [5.5, 15],
      [5, 15.5],
    ])
      expect(() => personalNumbers(month!, day!, '2026-10-05')).toThrow();
    expect(() => personalNumbers(5, 15, '2026-10-05[u-ca=hebrew]')).toThrow();
    expect(() => personalNumbers(5, 15, '1899-01-01')).toThrow();
  });
  it('normalizes lunar birthdays without using solar time or birth hour', () => {
    const lunar = normalizeBirth({
      calendar: 'lunar',
      year: 1993,
      month: 3,
      isLeapMonth: true,
      day: 15,
      hour: 6,
      minute: 0,
      timeUnknown: false,
      gender: 'male',
    });
    const chart = computeNumerology({ birth: lunar, date: '2026-10-05' });
    const gregorian = birth(lunar.local.year, lunar.local.month, lunar.local.day);
    expect(computeNumerology({ birth: gregorian, date: '2026-10-05' })).toEqual(chart);
  });
  it('dispatches deterministically with timezone-local dates and school metadata', () => {
    const result = compute({
      system: 'numerology',
      birth: birth(1990, 5, 15),
      name: 'John Doe',
      now,
    });
    expect(
      compute({ system: 'numerology', birth: birth(1990, 5, 15), name: 'John Doe', now }),
    ).toEqual(result);
    expect(result.meta.schoolUsed).toMatchObject({
      alphabet: 'pythagorean',
      yearBoundary: 'january_1',
    });
    const profile = normalizeBirth({
      calendar: 'gregorian',
      year: 1990,
      month: 5,
      day: 15,
      timeUnknown: true,
      gender: 'unspecified',
      place: { name: 'NY', lat: 40, lng: -74, tz: 'America/New_York' },
    });
    expect(
      NumerologyChartSchema.parse(compute({ system: 'numerology', birth: profile, now }).chart)
        .personal.targetDate,
    ).toBe('2026-10-04');
    expect(() => compute({ system: 'numerology', now })).toThrow();
    expect(() =>
      compute({
        system: 'numerology',
        birth: profile,
        now,
        options: { school: { unknown: true } },
      }),
    ).toThrow();
  });
  it('rejects unsupported names and invalid output snapshots at boundaries', () => {
    for (const name of ['张三', 'José', 'John123', '<script>'])
      expect(NumerologyNameSchema.safeParse(name).success).toBe(false);
    expect(NumerologyNameSchema.safeParse('O’Neil Smith-Jones').success).toBe(true);
    expect(
      ReadingRequestSchema.safeParse({
        system: 'numerology',
        name: '123',
        idempotencyKey: '00000000-0000-4000-8000-000000000000',
      }).success,
    ).toBe(false);
    expect(() =>
      computeNumerology({ birth: birth(1990, 5, 15), name: '123', date: '2026-10-05' }),
    ).toThrow();
    const chart = computeNumerology({ birth: birth(1990, 5, 15), date: '2026-10-05' });
    expect(chart.cycles.map((c) => c.number)).toEqual([3, 4, 5, 6, 7, 8, 9, 1, 2]);
    expect(chart.cycles.filter((c) => c.isCurrent)).toHaveLength(1);
    expect(chart.compatibility).toEqual({ first: 3, second: 6, basis: 'birthday' });
    expect(
      NumerologyChartSchema.safeParse({ ...chart, lifePath: { ...chart.lifePath, number: 10 } })
        .success,
    ).toBe(false);
  });
});
