export const traditionalTerms: ReadonlyArray<readonly [string, string]> = [
  ['軟件', '軟體'],
  ['體系', '體系'],
  ['數據', '資料'],
  ['信息', '資訊'],
  ['默認', '預設'],
  ['賬戶', '帳戶'],
  ['賬號', '帳號'],
  ['登錄', '登入'],
  ['打印', '列印'],
  ['鼠標', '滑鼠'],
  ['視頻', '影片'],
  ['羅喉', '羅睺'],
  ['罗睺', '羅睺'],
  ['幹坤', '乾坤'],
  ['幹卦', '乾卦'],
  ['鬥數', '斗數'],
  ['姓名錶', '姓名表'],
  ['字母錶', '字母表'],
  ['數字錶', '數字表'],
  ['錶格', '表格'],
  ['裏', '裡'],
  // DESIGN-GAP: Correct ambiguous locative phrases without rewriting geographic names or distance units containing 里.
  ['生日里', '生日裡'],
  ['姓名里', '姓名裡'],
  ['命盤里', '命盤裡'],
  ['數字里', '數字裡'],
  ['九宮格里', '九宮格裡'],
];
