import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
// DESIGN-GAP: Keep documented next-intl 3.x; narrowly suppress non-applicable advisories and verify the extract-zip security backport before audit.
const routing = await readFile('apps/web/i18n/routing.ts', 'utf8');
assert.match(routing, /localePrefix:\s*'always'/);
const nextConfig = await readFile('apps/web/next.config.ts', 'utf8');
assert.doesNotMatch(nextConfig, /precompile|experimental\.messages/);
const vitest = await readFile('vitest.config.ts', 'utf8');
assert.match(vitest, /environment:\s*'node'/);
assert.doesNotMatch(vitest, /browser:/);
const lhci = createRequire(require.resolve('@lhci/cli/package.json'));
const lighthouse = createRequire(lhci.resolve('lighthouse/package.json'));
const puppeteer = createRequire(lighthouse.resolve('puppeteer-core/package.json'));
const browsers = createRequire(puppeteer.resolve('@puppeteer/browsers'));
const extracted = browsers.resolve('extract-zip');
const source = await readFile(extracted, 'utf8');
assert.match(source, /Archive symlink target escapes extraction root/);
assert.match(source, /flags: 'wx'/);
console.log('Context-specific audit exceptions verified. See scripts/compliance/README.md.');
