/** Deterministic bilingual practice prompts consumed by the offline content generator. */
export const synastryExercises = [
  [
    'overview',
    '谈共同目标',
    'shared goals',
    '各自列出最看重的三个目标，再寻找可同时满足的部分',
    'List three priorities separately and look for a step that serves both people',
  ],
  [
    'overview',
    '核对差异',
    'checking differences',
    '把一个不同意见写成两种具体需要，不急着选择谁正确',
    'Translate a disagreement into two concrete needs before judging either view',
  ],
  [
    'overview',
    '保留自主',
    'keeping autonomy',
    '为各自兴趣保留独立时间，再约定共同活动',
    'Reserve time for independent interests and then agree on a shared activity',
  ],
  [
    'communication',
    '复述确认',
    'reflecting back',
    '听完以后用自己的话复述，并邀请对方纠正',
    'Reflect back what you heard and invite a correction',
  ],
  [
    'communication',
    '明确请求',
    'clear requests',
    '把希望对方做到的动作与时间范围说清楚',
    'Name the action you hope for and the time frame',
  ],
  [
    'communication',
    '选择时机',
    'timing conversations',
    '在双方都能专心的时候谈一个具体问题',
    'Choose a moment when both people can focus on one question',
  ],
  [
    'communication',
    '区分事实',
    'facts and interpretations',
    '分别记录可观察事实与自己的推测',
    'Separate an observable fact from your interpretation',
  ],
  [
    'communication',
    '检查语气',
    'checking tone',
    '问清楚一句话是提问、建议还是需要支持',
    'Ask whether a sentence is a question, a suggestion, or a request for support',
  ],
  [
    'communication',
    '倾听结束',
    'finishing a thought',
    '给对方说完的空间，再整理自己的回应',
    'Let the other person finish before organizing your response',
  ],
  [
    'love',
    '询问关心',
    'asking about care',
    '询问最近哪一种关心让对方感到舒适',
    'Ask which recent form of care felt welcome',
  ],
  [
    'love',
    '尊重边界',
    'respecting boundaries',
    '讨论亲密举动之前先确认双方是否愿意',
    'Check both people’s willingness before a gesture of closeness',
  ],
  [
    'love',
    '表达感谢',
    'expressing appreciation',
    '指出一个具体举动以及它带来的帮助',
    'Name a particular gesture and the help it offered',
  ],
  [
    'love',
    '独处需要',
    'time alone',
    '把独处时间与疏远感分开谈清楚',
    'Discuss time alone separately from feelings of distance',
  ],
  [
    'love',
    '日常陪伴',
    'everyday presence',
    '选择一种双方都愿意持续的小活动',
    'Choose a small activity both people want to continue',
  ],
  [
    'love',
    '调整期待',
    'adjusting expectations',
    '把想象中的关心方式与实际可做的事对照',
    'Compare an imagined form of care with what is feasible',
  ],
  [
    'values_money',
    '日常预算',
    'everyday budgets',
    '讨论一笔共同支出及各自可接受的范围',
    'Discuss one shared expense and each person’s acceptable range',
  ],
  [
    'values_money',
    '资源边界',
    'resource boundaries',
    '写清共同资源与各自自主决定的部分',
    'Distinguish shared resources from independent decisions',
  ],
  [
    'values_money',
    '时间分配',
    'sharing time',
    '把休息、工作与共同活动放到同一张计划里',
    'Put rest, work, and shared activities on one plan',
  ],
  [
    'values_money',
    '家务分工',
    'household responsibilities',
    '按可用时间安排一项家务并定期调整',
    'Assign one household responsibility based on available time and revisit it',
  ],
  [
    'values_money',
    '确认优先',
    'checking priorities',
    '说明一个决定对自己重要的原因',
    'Explain why one decision matters to you',
  ],
  [
    'values_money',
    '复盘支出',
    'reviewing expenses',
    '讨论体验与用途而不是互相评价花钱习惯',
    'Discuss usefulness and experience without judging spending habits',
  ],
  [
    'conflict',
    '暂停信号',
    'pause signals',
    '约定需要暂停时怎样说以及何时回来',
    'Agree on how to request a pause and when to return',
  ],
  [
    'conflict',
    '修复开头',
    'repair attempts',
    '用描述感受的句子重新开启对话',
    'Restart with a sentence that describes your own feeling',
  ],
  [
    'conflict',
    '避免泛化',
    'avoiding generalizations',
    '用最近一次经历替代对方总是怎样的评价',
    'Use one recent event instead of a judgment about what the other person always does',
  ],
  [
    'conflict',
    '承认影响',
    'acknowledging impact',
    '区分自己的意图与对方实际受到的影响',
    'Separate your intention from the effect experienced by the other person',
  ],
  [
    'conflict',
    '找共同点',
    'finding agreement',
    '先记录已经同意的部分再谈分歧',
    'Record what is already agreed before discussing differences',
  ],
  [
    'conflict',
    '具体调整',
    'specific changes',
    '选一个双方愿意改变的动作观察几次',
    'Choose one action both people are willing to change and observe several attempts',
  ],
  [
    'long_term',
    '每周复盘',
    'weekly reviews',
    '每周讨论一件合作顺畅的事和一件需要调整的事',
    'Each week discuss one thing that worked and one thing to adjust',
  ],
  [
    'long_term',
    '变更分工',
    'changing responsibilities',
    '当时间安排变化时重新确认分工',
    'Revisit responsibilities when schedules change',
  ],
  [
    'long_term',
    '个人成长',
    'individual growth',
    '给各自学习与兴趣留出空间',
    'Leave room for each person’s learning and interests',
  ],
  [
    'long_term',
    '庆祝进展',
    'noticing progress',
    '记录一个共同完成的小目标',
    'Record one small goal completed together',
  ],
  [
    'long_term',
    '重谈承诺',
    'revisiting commitments',
    '把重要期待写成可以讨论与修改的约定',
    'Turn important expectations into agreements that can be discussed and revised',
  ],
  [
    'long_term',
    '保留选择',
    'keeping choice',
    '定期确认双方仍然愿意参与哪些共同安排',
    'Regularly confirm which shared arrangements both people still wish to join',
  ],
] as const;
